FIND_PATH(ZRTPCPP_INCLUDE_DIR libzrtpcpp/zrtpccrtp.h)
FIND_LIBRARY(ZRTPCPP_LIBRARIES NAMES zrtpcpp)

IF(ZRTPCPP_INCLUDE_DIR AND ZRTPCPP_LIBRARIES)
	SET(ZRTPCPP_FOUND TRUE)
ENDIF(ZRTPCPP_INCLUDE_DIR AND ZRTPCPP_LIBRARIES)

IF(ZRTPCPP_FOUND)
	IF (NOT Zrtpcpp_FIND_QUIETLY)
		MESSAGE(STATUS "Found libzrtpcpp includes:	${ZRTPCPP_INCLUDE_DIR}/libzrtpcpp/zrtpccrtp.h")
		MESSAGE(STATUS "Found libzrtpcpp library:	${ZRTPCPP_LIBRARIES}")

		SET(ZRTPCPP_INCLUDE_DIR ${ZRTPCPP_INCLUDE_DIR} "${ZRTPCPP_INCLUDE_DIR}/libzrtpcpp")
	ENDIF (NOT Zrtpcpp_FIND_QUIETLY)
ELSE(ZRTPCPP_FOUND)
	IF (Zrtpcpp_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could NOT find libzrtpcpp development files")
	ENDIF (Zrtpcpp_FIND_REQUIRED)
ENDIF(ZRTPCPP_FOUND)
