FIND_PATH(LIBSNDFILE_INCLUDE_DIR sndfile.h)

SET(LIBSNDFILE_NAMES ${LIBSNDFILE_NAMES} sndfile)
FIND_LIBRARY(LIBSNDFILE_LIBRARY NAMES ${LIBSNDFILE_NAMES} PATH)

IF(LIBSNDFILE_INCLUDE_DIR AND LIBSNDFILE_LIBRARY)
	SET(LIBSNDFILE_FOUND TRUE)
ENDIF(LIBSNDFILE_INCLUDE_DIR AND LIBSNDFILE_LIBRARY)

IF(LIBSNDFILE_FOUND)
	IF(NOT LibSndfile_FIND_QUIETLY)
		MESSAGE(STATUS "Found LibSndfile: ${LIBSNDFILE_LIBRARY}")
	ENDIF (NOT LibSndfile_FIND_QUIETLY)
ELSE(LIBSNDFILE_FOUND)
	IF(LibSndfile_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find sndfile")
	ENDIF(LibSndfile_FIND_REQUIRED)
ENDIF (LIBSNDFILE_FOUND)
