name: Build

on: [push, pull_request]

env:
  FLAGS: "-DWITH_QT5=ON -DWITH_ALSA=ON -DWITH_GSM=ON -DWITH_SPEEX=ON -DWITH_ZRTP=OFF"
  # (qttools5-dev-tools is explicitly included because of Debian bug #835295)
  PACKAGES: "libasound2-dev libgsm1-dev libspeex-dev libspeexdsp-dev qtdeclarative5-dev qttools5-dev qttools5-dev-tools"

jobs:
  build:
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    strategy:
      matrix:
        include:
          # Test building with GCC and Clang (current default version)
          - gcc: default
          - clang: default

          # Test some other GCC/Clang versions, namely the lowest and highest
          # available at the moment, making sure to include at least one for
          # each Ubuntu release provided by GitHub Actions.
          #
          # (GCC 4.8 is omitted due to issue #31)
          - gcc: 5
            os: ubuntu-18.04
          - gcc: 11
            os: ubuntu-20.04
          - clang: 3.9
            os: ubuntu-18.04
          - clang: 14
            os: ubuntu-20.04

          # Test with all options disabled
          - FLAGS: "-DWITH_QT5=OFF -DWITH_ALSA=OFF -DWITH_GSM=OFF -DWITH_SPEEX=OFF -DWITH_ZRTP=OFF"
            # The empty string would evaluate to false and fail to override
            # $PACKAGES, so we use this true-but-still-empty hack instead.
            PACKAGES: " "

          # Test building with bcg729
          - BUILD_BCG729: "master"
            FLAGS: "-DWITH_QT5=OFF -DWITH_ALSA=OFF -DWITH_G729=ON"
            PACKAGES: "git ca-certificates"
          # Also test the old pre-1.0.2 API (see issue #104)
          - BUILD_BCG729: "1.0.1"
            BUILD_BCG729_AUTOTOOLS: "Y"
            FLAGS: "-DWITH_QT5=OFF -DWITH_ALSA=OFF -DWITH_G729=ON"
            PACKAGES: "git ca-certificates pkg-config libtool automake autoconf"

    steps:
      # Install all packages necessary for this build
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get -y install bison cmake flex libccrtp-dev libmagic-dev libreadline-dev libsndfile1-dev libucommon-dev libxml2-dev linux-libc-dev $PACKAGES
        env:
          PACKAGES:     ${{ matrix.PACKAGES || env.PACKAGES }}

      # Set up a specific version of GCC or Clang if matrix.gcc/clang is set
      #
      # Note: This must come *after* `apt-get update` above, see:
      #       https://github.com/egor-tensin/setup-clang/issues/5
      - name: Set up GCC (${{ matrix.gcc || 'n/a' }})
        if: ${{ matrix.gcc }}
        uses: egor-tensin/setup-gcc@v1
        with:
          # Note that these actions use 'latest' to designate the (usually not
          # latest) default version.  This would result in somewhat confusing
          # output, so we use 'default' instead and perform our own renaming.
          version: ${{ ((matrix.gcc == 'default') && 'latest') || matrix.gcc }}
      - name: Set up Clang (${{ matrix.clang || 'n/a' }})
        if: ${{ matrix.clang }}
        uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ ((matrix.clang == 'default') && 'latest') || matrix.clang }}

      # Download and build bcg729 if necessary for this build
      - name: Download and build bcg729
        run: if [ "$BUILD_BCG729" ]; then git clone https://gitlab.linphone.org/BC/public/bcg729.git --branch "$BUILD_BCG729" && (cd bcg729 && if [ "$BUILD_BCG729_AUTOTOOLS" ]; then ./autogen.sh && ./configure; else cmake .; fi && make && sudo make install); fi
        env:
          BUILD_BCG729:           ${{ matrix.BUILD_BCG729 }}
          BUILD_BCG729_AUTOTOOLS: ${{ matrix.BUILD_BCG729_AUTOTOOLS }}

      # Everything is now set up, ready to checkout/configure/build/install

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure
        run: cmake -B ${{github.workspace}}/build ${{env.FLAGS}}
        env:
          FLAGS: ${{ matrix.FLAGS || env.FLAGS }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Install
        run: cmake --install ${{github.workspace}}/build
                    --prefix ${{github.workspace}}/_install
